### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by mikethreels**
Changelog

- Added top navbar including gradient colours
- Added background images
- Added aside section
- Added footer section

### CODE REVIEW

**Comment by mikethreels** [comment]
I closed and opened the pull request because I forgot to turn on stickler the first time.

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @mikethreels, great job with this project. The README looks good and PR has a title and a description :smile:  However, let us improve our code and make even better by addressing the comments below: :+1: 

- Kindly add a link to the copyright
cpp
- Kindly fix the horizontal scroll. A quick fix is to set the width to 100%
- There are some repeating code in the CSS file, let us apply the DRY rule
- Let us add how to clone the project to our README file

Kindly make these changes and submit another code review :slightly_smiling_face: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo)

**Comment by mikethreels** [comment]
Changelog
- compared all links with original website and fixed where needed
- fixed horizontal scroll
- cleaned up CSS
- added how to clone in the README.

**Review by rammazzoti2000 — APPROVED** [review]
### Hello @mikethreels :wave: I am Alex (TSE)
## Project Approved :rocket: 
Great job on implementing the changes asked by the previous TSE
The project meets all requirements and for that this project is approved, feel free to merge whenever you're ready :tada: :rocket: 
### 
Cheers and Happy coding! :clap: 
##### Code review by Alexandru Bangau
(Feel free to contact me on slack by the handle of alexandru if you have any additional question)</em>

### :heavy_check_mark:  Status: Project Approved

**Pull request merged**
